### ISSUE TITLE
NOS 2.8.7 telnet issues

### ISSUE THREAD

**Issue by PashPaw** [kej715/DtCyber#21]
**Describe the bug**
Cannot telnet into NOS 2.8.7 on port 23 after the webterm updates.  

**To Reproduce**
1. Open a telnet client like PuTTY or the included webterm.
2. Try to connect to the NOS 2.8.7 host on port 23.
3. Fails to connect on port 23 and just displays `Connecting to host - please wait ...`
4.  On PuTTY, it just doesn't do anything.  No login prompt.  Disconnects on Webterm.

**Expected behavior**
I expected it to telnet into NOS 2.8.7 like usual and it failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/26450290/193955725-24f7ce73-22f5-4e83-949c-18c438075453.png).
![image](https://user-images.githubusercontent.com/26450290/193955818-baba75c8-ad72-4c6e-b8a5-3ed549e72685.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi, PuTTY
 - Version: Vivaldi:  5.4.2753.51 (Stable channel) (64-bit), PuTTY: 0.76

**Additional context**
No modifications to cyber.ini and this machine isn't running a telnet server.

**Comment by kej715** [comment]
Hi Paula,

I am unable to reproduce the problem reported. DtCyber is a telnet server,
and it should be listening for connections on TCP port 23. Does the
"netstat -an" command show a process listening on port 23? When DtCyber
starts, does it issue any error messages regarding inability to listen on
port 23? You might need to start it "manually" using the command
"x64\Release\DtCyber\DtCyber.exe" to see verbose startup messages. If
DtCyber is unable to listen on port 23, or client applications are unable
to connect to port 23, then perhaps your Windows security software (e.g.,
Windows firewall) is preventing DtCyber from listening, or clients from
connecting?

thanks,
Kevin

**Comment by kej715** [comment]
Hi Paula,

Yes, please make your disk images available to me.

It's probably coincidental that rebuilding IAF seems to fix the problem. It
seems very unlikely that IAF would be corrupted by the failure of an
optional product installation procedure. In addition, the screenshots
provided earlier indicate that the attempt to connect to TCP port 23
failed. IAF is not listening on that port. The MDI emulation module should
be listening on that port, and when a connection is made successfully, the
MDI emulator issues a message to confirm that the connection is
established, and then it begins communicating with NAM. Initially, NAM
connects the terminal to application NVF (Network Validation Facility). NVF
issues the operating system banner and prompts the user for FAMILY,
USERNAME, and PASSWORD. It might also prompt for APPLICATION, but not
usually on an initial login. If correct FAMILY, USERNAME, and PASSWORD are
entered by the user, then NVF passes the connection to IAF, so IAF does not
get involved until a successful login has completed.

None of that was occurring in the screenshots provided. The screenshots
show no indication that the initial TCP connection was made. If a
connection had been made, then the MDI would have issued a message to
confirm it, and then you would see the operating system banner and login
prompts issued by NVF.

I still suspect that a firewall or similar security software is preventing
usage of port 23. Port 23 is kind of special in that it is usually used by
generic Telnet servers. CYBIS uses port 8005 which is not special in that
sense.

I suggest that you try changing the port number on which DtCyber is
listening for interactive terminal connections. Line 130 of the NOS 2.8.7
cyber.ini file contains this line:

     terminals=*23*,0x04,16,telnet

try changing it to:

     terminals=*8023*,0x04,16,telnet

This will cause DtCyber to listen for interactive terminal connections on
port 8023 instead of port 23. After doing this and restarting DtCyber, try
connecting to port 8023 using putty. If you're able to connect, then this
probably confirms that security software is preventing usage of port 23.
You will also need to change the web terminal server configuration to align
with the change in port number. Line 22 of webterm\config.json has this
line:

     "port": 23,

you will need to change it to:

     "port": 8023,

if you want to use the browser-based terminal emulators.

cheers,
Kevin

**Comment by PashPaw** [comment]
Hi,

Aha! I didn't know what the exact internals were, so thanks.  I'm still new to NOS 2 (and CDC systems as a whole).

And I had configured Windows Firewall for dtCyber and port 23 was working fine before this. I also added an exception in Malwarebytes for where dtCyber resides.

And here's a link to the deadstart tape and disk images:

https://drive.google.com/file/d/1OIHigRz-EK4xquWEFeD94catJd1Uh3UC/view?usp=sharing

Thanks,
Paula.

**Comment by kej715** [comment]
Hi Paula,

I am not able to reproduce the problem using the disk and tape images you
provided. Using the images provided, I am able to connect successfully to
Telnet port 23 directly using an ordinary Telnet client, and the web
terminal interface works too.

thanks,
Kevin

**Comment by PashPaw** [comment]
Thanks.  I guess whatever it was just a hiccup with something.
