### ISSUE TITLE
Redesigned printer driver lp3000.c does not handle multiple device control commands properly

### ISSUE THREAD

**Issue by bug400** [kej715/DtCyber#35]
**Describe the bug**
After redesigning printer emulation, page ejects do not happen under NOS/BE in some cases,

**To Reproduce**
Run DtCyber with NOS/BE, start JANUS. In the printer output file, the leading "1" is missing for the banner pages.
DtCyber printer definition:
LP501,5,0,12,3555
NOS/BE EST definition:
LP501,5,0,12,3555

Activating debug output for the lp3000.c shows, that multiple printer control commands are sent to the driver before an
output request is issued (see attached log file). In the current version of the printer driver, the last control command "PrintDouble" overwrites "PrintEject".

**Expected behavior**
Enable printer drivers to handle multiple control commands for output requests.

**Screenshots**
None, see attached log file and printer output file
[attachment.zip](https://github.com/kej715/DtCyber/files/10153010/attachment.zip)

**Desktop (please complete the following information):**
 - Debian Bullseye
 - DtCyber 5.7.23

**Comment by kej715** [comment]
Corrective code has been pushed to the repo. Please pull the code, test in your environment, and close this issue if you can confirm that the issue is resolved.

**Comment by bug400** [comment]
I attached two short printer output file, created with DtCyber 5.7.21 and 5.7.24, both with the same job output
[printfile_samples.zip](https://github.com/kej715/DtCyber/files/10175271/printfile_samples.zip):

- The 5.7.24 printer output file has a "T" as the first character in the printer output file, what I can't explain
- The ASA code "0" was replaced by "-" in the 5.7.24 printer output file, which is "space 3 lines" instead of "space 2 lines". In this case, the standard NOS/BE banner page will exceed the page length (standard OS config is 6 lpi, 60 lines per page)

**Comment by kej715** [comment]
The format effector character in column 1 of each line reflects the
function code(s) sent to the controller and printer. The format effector
"T" reflects that the operating system has sent a function code to request
8 lines/inch print density. The format effector "-" reflects that the
operating system has sent a function code to skip 3 lines. At 8 lines/inch,
the banner pages provided in the 5.7.24 sample will -NOT- overflow the
page. The number of lines printer per banner page is 65 (16 "-" x 3 + 12
lines block letters + 5 lines "MWMWM..."). At 8 lpi, 8.125 inches of paper
will be used, and a typical page is 8.5 inches by 14 inches.

The log sent previously confirms that the output is correct. For example,
here is a snippet from the top of the log:

709902997 PP:12 CH:12 f:0000 T:FcPrintRelease             >
709932050 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709934279 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709934839 PP:12 CH:12 f:0010 T:*Fc3555Sel8Lpi*              >
709937648 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709938705 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709939263 PP:12 CH:12 f:0004 T:*FcPrintEject*               >
709941077 PP:12 CH:12 f:0000 T:FcPrintRelease             >
709969848 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709970894 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709971431 PP:12 CH:12 f:0002 T:*FcPrintDouble*              >
709974801 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
709978007 PP:12 CH:12 f:1600 T:Fc6681Output               >
    6060
    prePrintFunc:0002  postPrintFunc:0000  doSuppress:FALSE


709980582 PP:12 CH:12 f:0000 T:FcPrintRelease             >
710011160 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
710012214 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
710012770 PP:12 CH:12 f:0002 T:*FcPrintDouble*              >
710016151 PP:12 CH:12 f:1300 T:Fc6681DevStatusReq         >
710019344 PP:12 CH:12 f:1600 T:Fc6681Output               >
    6060
    prePrintFunc:0002  postPrintFunc:0000  doSuppress:FALSE


The highlighted text shows the key function codes sent by the operating
system. We see here that it selects 8 lines/inch (function code
*Fc3555Sel8lpi* mapped to "T" effector), then it requests page eject
(function code *FcPrintEject* mapped to "1" effector), then it begins
printing lines. Each line printed is preceded by a request to skip two
lines (function code *FcPrintDouble* mapped to "-" effector), thus causing
two empty lines to appear before each printed line. Similarly function code
FcPrintSingle would cause one line to be skipped before printing, and no
function code issued before a line would cause no lines to be skipped (this
can be seen in the log where the block letters of the banner are being
printed).

If the same function codes were sent by the OS to the controller when the
5.7.21 output was produced, then that output is incorrect because the "0"
effectors should be "-". Also, the 5.7.21 output is missing the "T"
effector which selects 8 lines/inch.

**Comment by bug400** [comment]
Thank you for the extensive explanation. Now I have to look why on earth NOS/BE issues a 8lpi select request even though the system wide configuration is 6lpi.

**Comment by kej715** [comment]
Hi Joachim,

I installed the ready-to-run NOS/BE package and used it to do some
additional testing. I noticed that the printer definition in the cyber.ini
file does not match the actual NOS/BE equipment definition. Specifically,
the cyber.ini specifies that the controller type is 3555, but the function
codes issued by the operating system are clearly intended for a 3152. This
explains why NOS/BE appears to be selecting 8 lines/inch. The operating
system is issuing function code 0010 at the beginning of the job. This
function code selects 8 lpi with a 3555 controller, and it clears formats
with a 3152 controller.  The lp3000 debug log also shows that unrecognized
functions 0015 and 0016 are received when a test job is run. The test job
attempts to execute functions for selecting format channels 5 and 6. The
3152 controller functions for these are 0015 and 0016, respectively. These
function codes are not recognized by a 3555.

I recommend that you modify the cyber.ini file, and change all occurrences
of:

LP501,5,0,12,3555

to:

LP501,5,0,12,3152


cheers,
Kevin
